spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true
        use_sql_comments: true
      open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
      password:
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8